version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"   # use 3000 if running React dev server
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  db:
    image: postgres:15.14
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  appnet:

volumes:
  pgdata:
